[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  HUGO_VERSION = "0.126.1"
  HUGO_EXTENDED = "true"
  NODE_VERSION = "22"

[context.deploy-preview]
  command = "yarn build:preview"

  [[context.deploy-preview.plugins]]
    package = "netlify-plugin-cypress"
    [context.deploy-preview.plugins.inputs]
      record = true

[dev]
  framework = "hugo"
  targetPort = 3000